#!/bin/bash

#SBATCH --job-name=TRAIN     # Set the job name
#SBATCH --nodes 1
#SBATCH --tasks-per-node 1
#SBATCH --cpus-per-task 4
#SBATCH --gpus a100:1
#SBATCH --mem 32gb
#SBATCH --time 24:00:00

#load python module
module load anaconda3/2023.09-0

#Go to working directory and run script
cd /scratch/student/tcga-brca-transcriptome
python TCGA_BRCA_V3.py
